version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "/frontend/dist"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing source NPM dependencies...
      - cd frontend
      - npm install
      - npm install -g @angular/cli
      - npm i amazon-cognito-identity-js
  build:
    commands:
      - echo Build started
      - pwd
      - ng build
      - ls
      - pwd
      - ls
artifacts:
  files:
    - "**/*"
  base-directory: "/frontend/dist"
  discard-paths: yes
